#version 460
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) readonly buffer BufferA { float a[]; };
layout(set = 0, binding = 1, std430) readonly buffer BufferB { float b[]; };
layout(set = 0, binding = 2, std430) writeonly buffer BufferC { float c[]; };

layout(push_constant) uniform Push { uint n; } pc;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i < pc.n) c[i] = a[i] + b[i];
}
